AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: data-stream-provisioned
      ShardCount: 4
      StreamModeDetails:
        StreamMode: PROVISIONED
